// src/App.vue
<template>
  <div id="app">
    <nav>
      <router-link to="/">Home</router-link> |
      <router-link to="/about">About</router-link> |
      <router-link to="/projects">Projects</router-link> |
      <router-link to="/contact">Contact</router-link>
    </nav>
    <router-view/>
  </div>
</template>

<style>
#app {
  font-family: Avenir, Helvetica, Arial, sans-serif;
  max-width: 800px;
  margin: 0 auto;
  padding: 20px;
}

nav {
  padding: 20px;
  text-align: center;
}

nav a {
  font-weight: bold;
  color: #2c3e50;
  margin: 0 10px;
}

nav a.router-link-exact-active {
  color: #42b983;
}
</style>

// src/App.svelte
<script>
  let name = "John Doe";
  let title = "Web Developer";
  let about = "I build cool websites with Svelte.";
  let email = "your.email@example.com";
</script>

<main class="p-8 text-center">
  <h1 class="text-4xl font-bold">{name}</h1>
  <p class="text-xl mt-2">{title}</p>

  <section class="mt-6">
    <h2 class="text-2xl">About Me</h2>
    <p>{about}</p>
  </section>

  <section class="mt-6">
    <h2 class="text-2xl">Contact</h2>
    <a href="mailto:{email}" class="text-blue-500">{email}</a>
  </section>
</main>

<style>
  main {
    font-family: Arial, sans-serif;
    background-color: #f7f7f7;
    border-radius: 8px;
    max-width: 600px;
    margin: 0 auto;
  }

  h1, h2 {
    color: #333;
  }

  p, a {
    color: #555;
  }

  a:hover {
    text-decoration: underline;
  }
</style>
